### ISSUE TITLE
Using Xamarin Android

### ISSUE THREAD

**Issue by npfernandeztheillet** [DevEddy/PathsenseAndroidSdkGeofencingXamarinBinding#1]
Hello how are you?
I'm trying to replicate the java example on Xamarin Android (in c#) with your binding...but it seems does not work...
The code building, i can use the classes (i transcribe all code of the example in c#, but never receive handlers and messages.. 

Do you use the binding in Xamarin and works?

**Comment by DevEddy** [comment]
Hi there,

I used it here: https://github.com/DevEddy/Plugin.Geofencing/tree/25ac12387a164667602c736144b891a8e0ee5a82

Hope it helps.

// EDDY
